config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/demo', to: 'demos#bananas'
  # resources :blabs, except: [:new, :edit] # , only: [:index]
  
  root to: 'static_pages#root' # will render index of blabs at root url
  # if we go to "/" we will be taken to the root page
  
  # get '/blabs', to: 'blabs#index'
  #if I receive a get with this path, then do this action
  
  # post '/blabs', to: 'blabs#create'
  # get '/blabs/:id', to: 'blabs#show', as: 'blab'
  # patch '/blabs/:id', to: 'blabs#update'
  # delete '/blabs/:id', to: 'blabs#destroy'
  resources :blabs

  namespace :api, defaults: { format: 'json' } do
    resources :blabs, only: [:index, :create, :show]
    resources :users, only: [:show, :index, :create]
  end

  resources :users, only: [:new, :create]
  
  # 'resource' indicates we will only ever care about a singular session
  resource :session, only: [:new, :create, :destroy]
  
  # get '/set_cookie', to: 'blabs#set_cookie'
  # get '/get_cookie', to: 'blabs#get_cookie'
  # resources :blabs, except: [:edit] - this is how you do all routes with exceptions
  # resources :blabs, only: [:new, :edit]
end

app/models/blab.rb
# == Schema Information
#
# Table name: blabs
#
#  id         :bigint(8)        not null, primary key
#  author_id  :integer
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blab < ApplicationRecord
  # blabs has the foreign key of author_id so it 
  # will have a belongs_to association with users
  validates :body, presence: true

  # belongs_to association automatically validates
  # the presence of the foreign_key
  belongs_to :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
    # optional: true

  has_one :location,
    through: :author,
    source: :location
end

app/controllers/api/blabs_controller.rb
class Api::BlabsController < ApplicationController

  def index
    @blabs = Blab.all
    render json: @blabs
  end

  def show
    @blab = Blab.find(params[:id])
    render json: @blab
  end

  def create
    @blab = Blab.new(blab_params)
    @blab.author = User.all.sample # randomly assign a user until we set up frontend auth
    if @blab.save
      render json: @blab
    else
      render json: @blab.errors.full_messages, status: 422
    end
  end

  private

  def blab_params
    params.require(:blab).permit(:body)
  end  
  
end

app/controllers/blabs_controller.rb
class BlabsController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]
  #controller hook, cannot be used inside model

  def index
    @blabs = Blab.all.includes(:author)
    #the only way to pass information from controller to view is to use
    #instance variables
    #local variables will not be passed to the view

    # render json: blabs
    # render :test #this is the block given to the "yield" in application.html.erb
    #rails knows where to find this test view inside the blabs folder
    #and finds test.html.erb
    render :index
    #RESTful convention is we want to match the name of the controller action
  end

  def show
    @blab = Blab.find(params[:id])
    # render json: blab
    render :show
  end

  def create
    # need to use Postman to test this now
    # author = User.all.sample # random author
    @blab = current_user.authored_blabs.new(blab_params)
    # @blab.author = current_user
    if @blab.save # returns true/false
      # render json: blab
      redirect_to blab_url(@blab)
   
    else
      # render json: blab.errors.full_messages, status: 422
      flash.now[:errors] = @blab.errors.full_messages
      # typically, flash.now is for rendering
      # whereas flash is for redirecting
      # redirect_to new_blab_url
      render :new, status: 422
    end
  end

  def update
    blab = current_user.authored_blabs.find(params[:id])
    # can either redirect or render, NOT BOTH
    if blab.update(blab_params)
      # redirect the user to the show page
      redirect_to blab_url(params[:id])
      #We redirect here, because once the user is updated,
      #the update function completed it's job and we want to 
      #start a new HTTP cycle by redirecting to show
      #This is separation of responsibilities
    else 
      flash[:errors] = blab.errors.full_messages
      redirect_to blab_url(params[:id])
      # render json: blab.errors.full_messages
    end
  end

  def destroy
    blab = current_user.authored_blabs.find(params[:id])
    #do not need to have an instance variable, because this data is not being sent to the view
    
    blab.destroy
    # redirect to blabs index
    redirect_to blabs_url
  end

  def new
    @blab = Blab.new
    #this will give us a blank default Blab object that we can use in the views

    # render :new
    # If nothing is rendered or redirected, Rails knows to look for
    # the RESTful convention template which in this case would be
    # new.html.erb (the name of the method .html.erb)
  end

  def edit
    @blab = current_user.authored_blabs.find_by(id: params[:id])
    if @blab
      render :edit
    else 
      flash[:errors] = ["You cannot edit this blab"]
      redirect_to blab_url(params[:id])
    end
  end

  def get_cookie
    my_cookie = flash[:errors]
    if my_cookie
      render plain: "Here's your cookie: #{my_cookie}"
    else
      render plain: "You haven't set a cookie called :my_cookie yet"
    end
  end

  def set_cookie
    maybe_cookie = [params[:my_cookie]]

    if maybe_cookie
      flash.now[:errors] = maybe_cookie
      render plain: "I am setting your cookie: #{flash[:errors]}"
    else
      render plain: "You must provide a cookie"
    end
  end

  private

  def blab_params # will return a hash-like object
    # will expect blab to be a key and body to be a key inside
    # of the blab key eg. {blab: {body: "hey derr"}}
    params.require(:blab).permit(:body) # returns {"body": "hey derr"}
  end
end

app/views/blabs/_form.html.erb
<% if edit %>
    <% action = blab_url(blab) %>
<% else %>
    <% action = blabs_url %>
<% end %>


<form action="<%= action %>" method="POST">
<%= auth_token %>
<% if edit %>
    <input type="hidden" name="_method" value="PATCH">
<% end%>
    <label for="blab-body">Body</label>
    <input id="blab-body" type="text" name="blab[body]" value="<%= blab.body %>">
    <input type="submit" value="<%= edit ? "Edit the Blab" : "Blab the blab" %>">
</form>

app/views/blabs/edit.html.erb
<h1>Editting a blab!</h1>

<%= render "form", edit: true, blab: @blab %>

app/views/blabs/index.html.erb
<h1>All the blabs!</h1>

<ul>
    <% @blabs.each do |blab| %>
        <li>
            <%= blab.author.username %> : <%= blab.body %> <a href="<%= blab_url(blab) %>">Blab!</a>
        </li>
    <% end %>
</ul>
<a href="<%= new_blab_url %>"><h1>Create a BLAB!!!</h1></a>

<!-- -->

app/views/blabs/new.html.erb
<h1>New Blab!</h1>

<%= render "form", edit: false, blab: @blab %>

app/views/blabs/show.html.erb
<h1>One single blab</h1>
<div>
    <p><%= @blab.body %></p>
    <br/>
    <p><%= "This blab was authored by: #{@blab.author.username}" %></p>
    <p><%= "This blab was written in : #{@blab.location.name}" %></p>
</div>

<a href="<%= edit_blab_url(@blab) %>"><h3>Edit the blab</h3></a>

<form action="<%= blab_url(@blab) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Deblab the blab">
</form>

app/views/blabs/test.html.erb
<h1>I'm the tester!</h1>

<% x= 3+2 %>

<div><%= "I'm here, look at me!" %></div>

<p><%= "The number is #{x}" %></p>

<% 5.times do |i| %>
    <h3><%= i %></h3>
<% end %>