config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/demo', to: 'demos#bananas'
  # resources :blabs, except: [:new, :edit] # , only: [:index]
  
  root to: 'static_pages#root' # will render index of blabs at root url
  # if we go to "/" we will be taken to the root page
  
  # get '/blabs', to: 'blabs#index'
  #if I receive a get with this path, then do this action
  
  # post '/blabs', to: 'blabs#create'
  # get '/blabs/:id', to: 'blabs#show', as: 'blab'
  # patch '/blabs/:id', to: 'blabs#update'
  # delete '/blabs/:id', to: 'blabs#destroy'
  resources :blabs

  namespace :api, defaults: { format: 'json' } do
    resources :blabs, only: [:index, :create, :show]
    resources :users, only: [:show, :index, :create]
  end

  resources :users, only: [:new, :create]
  
  # 'resource' indicates we will only ever care about a singular session
  resource :session, only: [:new, :create, :destroy]
  
  # get '/set_cookie', to: 'blabs#set_cookie'
  # get '/get_cookie', to: 'blabs#get_cookie'
  # resources :blabs, except: [:edit] - this is how you do all routes with exceptions
  # resources :blabs, only: [:new, :edit]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blabber</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript"> window.blabberURL = "<%= image_url('blabbers.jpg') %>" </script>
  </head>

  <body>
    <!-- <h1>I'm the application layout, look at me!</h1> -->

    <% if logged_in? %>
      <h1>Hello, <%= current_user.username %></h1>
      <form action="<%= session_url %>" method="POST">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Log In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>


    <%= yield %>
  </body>
</html>